FerretDB/dance

.github/workflows/dance.yml, .github/workflows/linters.yml
Sync FerretDB's and dance's build times, so dance tests run after the new Docker image is built.
See FerretDB/FerretDB#794.
=> Tweak schedule of daily builds

CONTRIBUTING.md
the `--remote` flag fetched submodules directly from main branch in mongo-go-driver which creates inconsistency with the current version in the dance tests.
=> Update misleading command in CONTRIBUTING.md

internal/tests_config.go, tests/diff.yml, tests/diff/collection_name_test.go, tests/diff/error_messages_test.go, tests/diff/helpers.go, tests/diff/null_strings_test.go
Closes FerretDB/FerretDB#806.
| Case | FerretDB | MongoDB | Status | 
|--|--|--|--| 
| `system.` |  fails: `system.` contains a dot |  fails: `system.` is a reserved prefix | skipped as both fail | 
| `_ferretdb_` | fails: `_ferretdb_` is a reserved prefix | pass | added | 
|  max length | 120  | 255 |  added | 
|  dots | fail | pass |  added | 
|  dashes | fail | pass |  added | 
Corresponding FerretDB PR [#844](https://github.com/FerretDB/FerretDB/pull/844).
=> Validate collection names

tests/diff.yml, tests/diff/document_validation_test.go, tests/diff/nested_arrays_test.go
Refs [#1305](https://github.com/FerretDB/FerretDB/issues/1305).
Plus two tests to pass: one for insert and one for update.
Plus five tests to fail: 
- `TestNestedArrays  Insert`'s subtest
- `TestNestedArrays  Insert` itself
- `TestNestedArrays  Update`'s subtest
- `TestNestedArrays  Update` itself
- `TestNestedArrays`.
=> Don't support nested arrays

tests/diff.yml, tests/diff/insert_test.go
When insert command is called, insert documents must not have duplicate keys.
Refs https://github.com/FerretDB/FerretDB/issues/1263.
Depends on https://github.com/FerretDB/FerretDB/pull/1391.
=> Duplicate keys are not allowed in `insert` documents

tests/diff.yml, tests/diff/debug_error_test.go, tests/diff/document_validation_test.go
Closes FerretDB/FerretDB#640.
This PR introduces tests for a new `debugError` command, but it also temporary fixes one failing test that was pushed to the main branch because of the recent bug that made dance flaky.
=> Add `debugError` diff tests

tests/diff.yml, tests/diff/names_test.go
After [#1582](https://github.com/FerretDB/FerretDB/pull/1582).
Closes [#1321](https://github.com/FerretDB/FerretDB/issues/1321).
=> Allow `-` in database names

.github/workflows/conform-pr.yml
See FerretDB/github-actions#122.
=> Do not handle `no ci` in one job

tests/diff/document_validation_test.go, tests/diff/helpers.go, tests/diff/insert_test.go, tests/diff/nested_arrays_test.go
In the case of the `insert` operation, the error that should be returned is `mongo.WriteException`, not `mongo.CommandError`.
It was fixed in FerretDB here - https://github.com/FerretDB/FerretDB/pull/1673, and diff tests need to be fixed too.
=> Fix type of error that need to be checked for `insert`

tests/mongo.yml
=> Add more core jstests

tests/diff.yml, tests/diff/float_values_test.go, tests/diff/negative_zero_test.go, tests/diff/update_test.go, tests/mongo.yml
Closes FerretDB/FerretDB#625. 
This tests differences introduced in FerretDB/FerretDB#1760.
* `+INF` upon $mul operator returns error
* `-0` negative zero is converted to `0` positive zero everywhere including insert and update operation.
=> `$mul` returns validation error on unsupported +INF result

tests/mongo.yml
Closes https://github.com/FerretDB/dance/pull/360.
We had to remove [all.js](https://github.com/mongodb/mongo/blob/9b4ddb11af242d7c8d48181c26ca091fe4533642/jstests/core/query/all/all.js#L24) because it silently fails inserting a nested array which only became apparent now.
=> Update `mongo` tests configurations

internal/jstest/jstest.go
I hard coded a value of 20 for now.
=> Limit the number of parallel files for `jstest` runner

tests/mongo-go-driver.yml
We had some breakage due to FerretDB/FerretDB/pull/2244 with unimplemented index options. This just fixes that.
=> Fix Go driver config

.github/workflows/dance.yml, Taskfile.yaml
Closes FerretDB/FerretDB#2086.
https://github.com/FerretDB/dance/actions/runs/4691597157 6.9 - 11.9 KB
https://github.com/FerretDB/dance/actions/runs/4692780544 2.47 - 2.89 KB.
=> Compress CI artifacts

.github/workflows/dance.yml, cmd/dance/main.go, internal/command/command.go, internal/ycsb/ycsb.go, tests/ycsb-workloada.yml, tests/ycsb-workloadc.yml, tests/ycsb/workloads/workload_template, tests/ycsb/workloads/workloada, tests/ycsb/workloads/workloadb, tests/ycsb/workloads/workloadc, tests/ycsb/workloads/workloadd, tests/ycsb/workloads/workloade, tests/ycsb/workloads/workloadf
This runner is one-per-test, so there is no need to collect output.
=> Stream go-ycsb output

tests/diff/dbstats_scale_test.go
`scale` parameter can now store an int64 because of [this](https://github.com/FerretDB/FerretDB/commit/263c3fe70be732b0283dbfa97da7f920a14f8e08#diff-96ce309aaf377642b38ebb97647a854ffe20758797f6fab92081955f54c9ef5bR42).
=> Fix diff test

cmd/dance/main.go, go.mod, go.sum
Closes #327.
Created a new PR to avoid having to deal with merge conflicts on abandoned [PR](https://github.com/FerretDB/dance/pull/327).
We should calculate the pass rate cumulatively for each segment of `dbaas_core` _then_ log to CI. This can be done in a follow up PR.
=> Log the pass rate on CI

internal/ycsb/ycsb.go, internal/ycsb/ycsb_test.go
**Note:** in the `go-ycsb` code I see json as output format being mentioned. It would be easier to parse from JSON, but I don't see a way to set it. 
Closes #943.
=> Parse metrics produced by `go-ycsb`

docker-compose.yml, internal/configload/configload.go, projects/dotnet-example.yml, projects/java-example.yml, projects/mongo-tools.yml, projects/nodejs-example.yml, projects/python-example.yml, projects/ycsb-workloada.yml, projects/ycsb-workloada2.yml, projects/ycsb-workloadb.yml, projects/ycsb-workloadb2.yml, projects/ycsb-workloadc.yml, projects/ycsb-workloadc2.yml
=> Add v2 dev databases
