FerretDB/dance

- Makefile
> Make `Makefile` a bit harder to misuse

- tests/ferret.yml
- tests/ferret/core_test.go
Refs FerretDB/FerretDB#257.
Refs FerretDB/FerretDB#331.
> Add tests for `$elemMatch` projection operator

- .github/workflows/dance.yml
- tests/ferret.yml
- tests/ferret/core_test.go
https://github.com/FerretDB/FerretDB/pull/369
> Commands are case-sensitive

- tests/ferret/core_test.go
> Support `$eq` comparision operator

- .github/workflows/conform-pr.yml
- .github/workflows/dance.yml
- .github/workflows/linters.yml
> Make it easier to trigger rebuilds

- CONTRIBUTING.md
- tests/diff.yml
- tests/diff/null_strings_test.go
> Add diff tests for NUL `\0` strings

- tests/diff.yml
- tests/diff/helpers.go
- tests/diff/names_test.go
- tests/diff/setup.go
Closes https://github.com/FerretDB/FerretDB/issues/807.
Refs https://github.com/FerretDB/FerretDB/pull/913.
> Validate database names

- README.md
Refs FerretDB/FerretDB#1181.
After FerretDB/FerretDB#1183.
> Update diff documentation link

- .github/workflows/conform-pr.yml
That should make restarts easier.
> Do not cancel in-progress CI runs

- tests/mongo-go-driver.yml
> Update Go driver tests to make CI pass

- tests/diff.yml
- tests/diff/float_values_test.go
After [#1401](https://github.com/FerretDB/FerretDB/pull/1401)
Refs [#1151](https://github.com/FerretDB/FerretDB/issues/1151).
> Deprecate float values

- tests/diff.yml
- tests/diff/document_validation_test.go
- tests/diff/float_values_test.go
See also https://github.com/FerretDB/FerretDB/pull/1622.
> Add diff tests for infinity cases

- internal/jstest/jstest.go
- tests/mongo.yml
They will become uncommon very soon.
> Update `mongo` tests configurations

- cmd/dance/main.go
- docker-compose.yml
- internal/gotest/gotest.go
- internal/jstest/jstest.go
- tests/mongo.yml
> Add globs in `jstest` runner

- .gitignore
- tests/mongo-tools.yml
- tests/mongo-tools/dump_restore_test.go
- tests/mongo-tools/export_import_test.go
- tests/mongo-tools/helpers.go
> Add tests for `mongoimport` and `mongoexport`

- internal/config.go
- internal/config_test.go
- internal/test_results.go
- internal/tests_config.go
- internal/yaml.go
> Add an ignore category for tests

- tests/mongo.yml
Closes #326.
In [SERVER-64473](https://jira.mongodb.org/browse/SERVER-64473) they have re-organized the core js suite. This PR resolve that issue.
> Fix new core suite

- cmd/dance/main.go
- tests/diff/document_validation_test.go
- tests/mongo-tools/dump_restore_test.go
Closes FerretDB/FerretDB#2088.
Closes FerretDB/FerretDB#2089.
> Update validation tests

- internal/jstest/jstest.go
> Optimize `jstest` runner

- tests/mongo-go-driver.yml
> Fix Go driver for CI

- tests/mongo.yml
Small fixes to files and failures for #294.
> Fix `mongo` configuration

- tests/diff.yml
- tests/diff/dbstats_scale_test.go
- tests/diff/helpers.go
See also https://github.com/FerretDB/FerretDB/pull/2418.
> Add diff tests for `scale` param in `dbStats`

- internal/gotest/gotest.go
- tests/diff.yml
- tests/mongo-tools.yml
> Add `-race` flag when possible

- .github/workflows/dance.yml
- .gitmodules
- tests/java-example.yml
> Add java-example to CI

- tests/mongo-go-driver.yml
> Fix Go driver config

- tests/diff.yml
- tests/diff/names_test.go
We allow database names to start with numbers.
> Fix diff tests

- tests/diff.yml
- tests/diff/insert_test.go
Closes FerretDB/FerretDB#3235.
> Add test for different duplicate id handling

- internal/config/config.go
- internal/configload/configload.go
- internal/configload/configload_test.go
- tests/mongo-go-driver.yml
> Remove regex support

- internal/configload/configload.go
- internal/configload/configload_test.go
> Remove dependency on common section

- tests/mongo.yml
> Add capped collection tests

- docker-compose.yml
- tests/mongo-go-driver.yml
- tests/mongo.yml
> Add all tailable cursor tests

- cmd/dance/main.go
- tests/enmeshed-runtime.yml
> Fix enmeshed config

- .github/workflows/dance-trust.yml
> Fix trust configuration

- build/deps/mongo.Dockerfile
- build/deps/mongo6.Dockerfile
- build/deps/mongo7.Dockerfile
- docker-compose.yml
- tests/mongo-go-driver.yml
- tests/mongo.yml
> Use MongoDB 7

- .gitmodules
Just fixes the link and updates the submodule.
> Fix link to enmeshed submodule

- .gitmodules
> Add mongodb-benchmarking repo

- internal/config/runner.go
- internal/runner/command/command.go
- internal/runner/command/command_test.go
> Add teardown execution for runners

- .github/workflows/dance.yml
- CONTRIBUTING.md
- docker-compose.yml
- internal/configload/configload.go
- projects/dotnet-example.yml
- projects/java-example.yml
- projects/mongo-core-test.yml
- projects/mongo-tools.yml
- projects/nodejs-example.yml
- projects/python-example.yml
- projects/ycsb-workloada.yml
- projects/ycsb-workloada2.yml
- projects/ycsb-workloadb.yml
- projects/ycsb-workloadb2.yml
- projects/ycsb-workloadc.yml
- projects/ycsb-workloadc2.yml
> Add more databases to project configurations
